-- BRCS live schema fix — add all missing columns
ALTER TABLE assets ADD COLUMN IF NOT EXISTS callsign TEXT DEFAULT 'ASSET';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '🎯';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'LOGISTICS';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS current_heading FLOAT DEFAULT 0;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS current_speed FLOAT DEFAULT 0;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS fuel_pct FLOAT DEFAULT 100;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS ammo_pct FLOAT DEFAULT 100;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS threat_level TEXT DEFAULT 'GREEN';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS crew_count INT DEFAULT 1;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS alert_count INT DEFAULT 0;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS active BOOL DEFAULT true;
UPDATE zones SET active = true WHERE active IS NULL;
ALTER TABLE simulator_state ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
CREATE TABLE IF NOT EXISTS operations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  codename TEXT,
  op_type TEXT DEFAULT 'STRIKE',
  status TEXT DEFAULT 'PLANNING',
  priority TEXT DEFAULT 'MEDIUM',
  objective_lat FLOAT,
  objective_lon FLOAT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO operations (id, name, codename, op_type, status, priority, objective_lat, objective_lon)
VALUES ('00000000-0000-0000-0000-000000000001','Default Simulation','OP-DEFAULT','STRIKE','PLANNING','HIGH',28.626,77.228)
ON CONFLICT DO NOTHING;
